DROP TABLE IF EXISTS groups CASCADE;
CREATE TABLE Groups (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  owner_id INTEGER NOT NULL REFERENCES Players(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);