DROP TABLE IF EXISTS matches CASCADE;
CREATE TABLE Matches (
  id SERIAL PRIMARY KEY,
  game_id INTEGER NOT NULL REFERENCES Games(id),
  date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);