DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE Matches (
  id SERIAL PRIMARY KEY,
  winner_id INTEGER NOT NULL REFERENCES Players(id),
  loser_id INTEGER NOT NULL REFERENCES Players(id),
  game_id INTEGER NOT NULL REFERENCES Games(id),
  date DATE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
